# Generated by Django 5.2.9 on 2026-02-16 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='iteration',
            name='iteration_type',
            field=models.CharField(blank=True, choices=[('landco_devco', 'LandCo & DevCo'), ('assetco', 'AssetCo'), ('assetco_consolidated', 'AssetCo Consolidated'), ('consolidation', 'Project Consolidation')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='base_landco_devco_template',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_base_file_link', models.URLField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_project_assets', to=settings.AUTH_USER_MODEL)),
                ('project_assoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='management.project')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_project_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='iteration',
            name='asset_assoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='management.projectasset'),
        ),
    ]
