# Generated by Django 5.2.9 on 2026-02-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_iteration_iteration_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectasset',
            name='asset_unique_identifier',
            field=models.CharField(blank=True, help_text='Unique identifier like S2-CE-RI-RU-SF-VIL1-0001', max_length=100, null=True, unique=True),
        ),
    ]
