# Generated by Django 5.2.9 on 2026-02-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_projectasset_asset_unique_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectasset',
            name='asset_unique_identifier',
            field=models.CharField(blank=True, help_text='Unique identifier like S2-CE-RI-RU-SF-VIL1-0001', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='projectasset',
            unique_together={('project_assoc', 'asset_unique_identifier')},
        ),
    ]
