# Generated by Django 5.2.9 on 2026-02-18 09:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_projectasset_asset_unique_identifier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectasset',
            name='is_hospitality',
            field=models.BooleanField(default=False, help_text='True if this asset is a hospitality asset'),
        ),
        migrations.CreateModel(
            name='UserIterationPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_access', models.BooleanField(default=True)),
                ('write_access', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user_iteration_permissions', to=settings.AUTH_USER_MODEL)),
                ('iteration_assoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='management.iteration')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_user_iteration_permissions', to=settings.AUTH_USER_MODEL)),
                ('user_assoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iteration_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_assoc', 'iteration_assoc')},
            },
        ),
    ]
