# Generated by Django 5.2.9 on 2026-03-03 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_projectasset_is_hospitality_useriterationpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidatedIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('iteration_type', models.CharField(blank=True, max_length=20, null=True)),
                ('output_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iteration_assoc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consolidated_iteration', to='management.iteration')),
            ],
        ),
        migrations.CreateModel(
            name='JvIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('iteration_type', models.CharField(blank=True, max_length=20, null=True)),
                ('output_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iteration_assoc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jv_iteration', to='management.iteration')),
            ],
        ),
    ]
