# Generated by Django 5.2.9 on 2026-03-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_consolidatediteration_jviteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidatediteration',
            name='iteration_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='iteration_type',
            field=models.CharField(blank=True, choices=[('landco_devco', 'LandCo & DevCo'), ('assetco', 'AssetCo'), ('assetco_consolidated', 'AssetCo Consolidated'), ('consolidation', 'Project Consolidation')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='jviteration',
            name='iteration_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
