# Generated by Django 5.2.9 on 2026-03-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_consolidatediteration_iteration_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dim_period',
                'constraints': [models.UniqueConstraint(fields=('period_start', 'period_end', 'period_type'), name='uq_dim_period_start_end_type')],
            },
        ),
    ]
