# Generated by Django 5.2.9 on 2026-03-05 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_dimperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimDataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='management.dimdataitem')),
            ],
            options={
                'db_table': 'dim_dataitem',
                'ordering': ['parent_id', 'display_order', 'id'],
            },
        ),
    ]
