# Generated by Django 5.2.9 on 2026-03-10 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_dimdataitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimGlobalDataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dim_globaldataitem',
            },
        ),
        migrations.CreateModel(
            name='AssetIteration_Devco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('asset_class', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('typology', models.CharField(max_length=100)),
                ('construction_phase', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('asset_unique_id', models.CharField(max_length=150)),
                ('asset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_model', models.CharField(blank=True, max_length=100, null=True)),
                ('exit_counterparty', models.CharField(blank=True, max_length=100, null=True)),
                ('units', models.FloatField(blank=True, null=True)),
                ('developable_land_area', models.FloatField(blank=True, null=True)),
                ('master_plan_efficiency', models.FloatField(blank=True, null=True)),
                ('gross_land_area', models.FloatField(blank=True, null=True)),
                ('site_coverage_ratio', models.FloatField(blank=True, null=True)),
                ('site_coverage_area', models.FloatField(blank=True, null=True)),
                ('gross_floor_area', models.FloatField(blank=True, null=True)),
                ('built_up_area', models.FloatField(blank=True, null=True)),
                ('floor_plan_efficiency', models.FloatField(blank=True, null=True)),
                ('total_nsa_gla', models.FloatField(blank=True, null=True)),
                ('floor_area_ratio', models.FloatField(blank=True, null=True)),
                ('parking_bays', models.FloatField(blank=True, null=True)),
                ('devco_inclusion', models.CharField(blank=True, max_length=20, null=True)),
                ('jvjda_inclusion', models.CharField(blank=True, max_length=20, null=True)),
                ('venture_type', models.CharField(blank=True, max_length=100, null=True)),
                ('land_bank_override', models.CharField(blank=True, max_length=20, null=True)),
                ('holding_period', models.CharField(blank=True, max_length=20, null=True)),
                ('asset_devco_inclusion', models.CharField(blank=True, max_length=20, null=True)),
                ('asset_order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_iterations_devco', to='management.iteration')),
            ],
        ),
        migrations.CreateModel(
            name='AssetIteration_Landco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('asset_class', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('typology', models.CharField(max_length=100)),
                ('construction_phase', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('asset_unique_id', models.CharField(max_length=150)),
                ('asset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_model', models.CharField(blank=True, max_length=100, null=True)),
                ('exit_counterparty', models.CharField(blank=True, max_length=100, null=True)),
                ('units', models.FloatField(blank=True, null=True)),
                ('developable_land_area', models.FloatField(blank=True, null=True)),
                ('master_plan_efficiency', models.FloatField(blank=True, null=True)),
                ('gross_land_area', models.FloatField(blank=True, null=True)),
                ('site_coverage_ratio', models.FloatField(blank=True, null=True)),
                ('site_coverage_area', models.FloatField(blank=True, null=True)),
                ('gross_floor_area', models.FloatField(blank=True, null=True)),
                ('built_up_area', models.FloatField(blank=True, null=True)),
                ('floor_plan_efficiency', models.FloatField(blank=True, null=True)),
                ('total_nsa_gla', models.FloatField(blank=True, null=True)),
                ('floor_area_ratio', models.FloatField(blank=True, null=True)),
                ('parking_bays', models.FloatField(blank=True, null=True)),
                ('jvjda_inclusion', models.CharField(blank=True, max_length=20, null=True)),
                ('landco_inclusion', models.CharField(blank=True, max_length=20, null=True)),
                ('venture_type', models.CharField(blank=True, max_length=100, null=True)),
                ('land_bank_override', models.CharField(blank=True, max_length=20, null=True)),
                ('holding_period', models.CharField(blank=True, max_length=20, null=True)),
                ('asset_landco_inclusion', models.CharField(blank=True, max_length=20, null=True)),
                ('asset_order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_iterations_landco', to='management.iteration')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalInputsIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('module', models.CharField(max_length=100)),
                ('global_data_item', models.ForeignKey(db_column='globaldataitemid', on_delete=django.db.models.deletion.PROTECT, related_name='global_input_iterations', to='management.dimglobaldataitem')),
                ('iteration', models.ForeignKey(db_column='iterationid', on_delete=django.db.models.deletion.CASCADE, related_name='global_input_iterations', to='management.iteration')),
            ],
        ),
        migrations.CreateModel(
            name='NormalisedIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_jv', models.BooleanField(default=False)),
                ('asset_devco', models.ForeignKey(blank=True, db_column='asset_devco_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalised_iterations', to='management.assetiteration_devco')),
                ('asset_landco', models.ForeignKey(blank=True, db_column='asset_landco_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalised_iterations', to='management.assetiteration_landco')),
                ('data_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='normalised_iterations', to='management.dimdataitem')),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalised_iterations', to='management.iteration')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalised_iterations', to='management.dimperiod')),
            ],
        ),
        migrations.AddIndex(
            model_name='assetiteration_devco',
            index=models.Index(fields=['iteration'], name='management__iterati_4ca509_idx'),
        ),
        migrations.AddIndex(
            model_name='assetiteration_devco',
            index=models.Index(fields=['asset_unique_id'], name='management__asset_u_ea7707_idx'),
        ),
        migrations.AddIndex(
            model_name='assetiteration_devco',
            index=models.Index(fields=['region', 'city'], name='management__region_e8d6da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetiteration_devco',
            unique_together={('iteration', 'asset_unique_id', 'region', 'city', 'asset_class', 'sub_category', 'typology', 'asset_order')},
        ),
        migrations.AddIndex(
            model_name='assetiteration_landco',
            index=models.Index(fields=['iteration'], name='management__iterati_da3576_idx'),
        ),
        migrations.AddIndex(
            model_name='assetiteration_landco',
            index=models.Index(fields=['asset_unique_id'], name='management__asset_u_bf0ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='assetiteration_landco',
            index=models.Index(fields=['region', 'city'], name='management__region_671f36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetiteration_landco',
            unique_together={('iteration', 'asset_unique_id', 'region', 'city', 'asset_class', 'sub_category', 'typology', 'asset_order')},
        ),
        migrations.AddIndex(
            model_name='globalinputsiteration',
            index=models.Index(fields=['iteration'], name='management__iterati_53d9da_idx'),
        ),
        migrations.AddIndex(
            model_name='globalinputsiteration',
            index=models.Index(fields=['global_data_item'], name='management__globald_d208a9_idx'),
        ),
        migrations.AddIndex(
            model_name='globalinputsiteration',
            index=models.Index(fields=['module'], name='management__module_2af921_idx'),
        ),
        migrations.AddIndex(
            model_name='normalisediteration',
            index=models.Index(fields=['iteration', 'period'], name='management__iterati_91e2be_idx'),
        ),
        migrations.AddIndex(
            model_name='normalisediteration',
            index=models.Index(fields=['data_item'], name='management__data_it_badb08_idx'),
        ),
        migrations.AddIndex(
            model_name='normalisediteration',
            index=models.Index(fields=['asset_landco'], name='management__asset_l_0ae1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='normalisediteration',
            index=models.Index(fields=['asset_devco'], name='management__asset_d_d8ff90_idx'),
        ),
    ]
