# Generated by Django 5.2.9 on 2026-03-25 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_dimglobaldataitem_assetiteration_devco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitIteration_Assetco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.PositiveIntegerField(blank=True, null=True)),
                ('asset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_id', models.CharField(blank=True, max_length=150, null=True)),
                ('asset_address', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_id', models.CharField(blank=True, max_length=150, null=True)),
                ('unit_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_unit_type', models.CharField(blank=True, max_length=255, null=True)),
                ('gross_leasable_area', models.FloatField(blank=True, null=True)),
                ('tenant_id', models.CharField(blank=True, max_length=150, null=True)),
                ('tenant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lease_start_date', models.DateField(blank=True, null=True)),
                ('lease_tenure', models.FloatField(blank=True, null=True)),
                ('rent_free_duration', models.FloatField(blank=True, null=True)),
                ('cash_collection_start_date', models.DateField(blank=True, null=True)),
                ('lease_expiration_date', models.DateField(blank=True, null=True)),
                ('break_option_exercised', models.CharField(blank=True, max_length=50, null=True)),
                ('break_option_date', models.DateField(blank=True, null=True)),
                ('sales_density', models.FloatField(blank=True, null=True)),
                ('second_tenant', models.CharField(blank=True, max_length=255, null=True)),
                ('void_period_months', models.CharField(blank=True, max_length=50, null=True)),
                ('tenant_2_id', models.CharField(blank=True, max_length=150, null=True)),
                ('tenant_2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant_2_lease_start_date', models.DateField(blank=True, null=True)),
                ('tenant_2_lease_tenure', models.FloatField(blank=True, null=True)),
                ('tenant_2_rent_free_duration', models.FloatField(blank=True, null=True)),
                ('tenant_2_cash_collection_start_date', models.DateField(blank=True, null=True)),
                ('tenant_2_lease_expiration_date', models.DateField(blank=True, null=True)),
                ('tenant_2_break_option_exercised', models.CharField(blank=True, max_length=50, null=True)),
                ('tenant_2_break_option_date', models.DateField(blank=True, null=True)),
                ('tenant_2_sales_density', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iteration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_units', to='management.iteration')),
                ('project_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='management.projectasset')),
            ],
            options={
                'unique_together': {('project_asset', 'unit_id')},
            },
        ),
    ]
