# Generated by Django 5.2.9 on 2026-03-25 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_unititeration_assetco'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalisediteration',
            name='asset_unit',
            field=models.ForeignKey(blank=True, db_column='asset_unit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalised_iterations', to='management.unititeration_assetco'),
        ),
        migrations.AddIndex(
            model_name='normalisediteration',
            index=models.Index(fields=['asset_unit'], name='management__asset_u_88df84_idx'),
        ),
    ]
