# Generated by Django 5.2.9 on 2026-04-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_normalisediteration_asset_unit_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unititeration_assetco',
            unique_together={('iteration', 'unit_id')},
        ),
    ]
