# Generated by Django 5.2.9 on 2026-04-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_unititeration_assetco_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='unititeration_assetco',
            name='forecast_base_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unititeration_assetco',
            name='renewal_probability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unititeration_assetco',
            name='tenant_2_forecast_base_rent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
