# Generated by Django 5.2.9 on 2026-04-16 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_unititeration_assetco_forecast_base_rent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidationSourceCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consolidation_type', models.CharField(choices=[('assetco_consolidation', 'AssetCo Consolidation'), ('jv_consolidation', 'JV Consolidation'), ('project_consolidation', 'Project Consolidation')], max_length=32)),
                ('source_iteration_ids', models.BigIntegerField(blank=True, null=True)),
                ('source_iteration_type', models.CharField(blank=True, max_length=64, null=True)),
                ('source_reference_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_assoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidation_source_combinations', to='management.project')),
                ('target_iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_combinations', to='management.iteration')),
                ('user_assoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidation_source_combinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['target_iteration', 'consolidation_type'], name='management__target__06dcaa_idx'), models.Index(fields=['project_assoc', 'consolidation_type'], name='management__project_266e10_idx'), models.Index(fields=['user_assoc'], name='management__user_as_22e7ba_idx')],
            },
        ),
    ]
