# Generated by Django 5.2.9 on 2026-04-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_consolidationsourcecombination'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidationsourcecombination',
            name='scenario_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
