# Generated by Django 5.2.9 on 2026-04-28 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_consolidationsourcecombination_scenario_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConsolidationAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_unique_identifier', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_assoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_consolidation_assets', to='management.project')),
            ],
        ),
        migrations.AddField(
            model_name='normalisediteration',
            name='asset_project_consolidation',
            field=models.ForeignKey(blank=True, db_column='asset_project_consolidation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalised_iterations', to='management.projectconsolidationasset'),
        ),
        migrations.AddIndex(
            model_name='normalisediteration',
            index=models.Index(fields=['asset_project_consolidation'], name='management__asset_p_e224a6_idx'),
        ),
        migrations.AddIndex(
            model_name='projectconsolidationasset',
            index=models.Index(fields=['project_assoc', 'asset_unique_identifier'], name='management__project_73655c_idx'),
        ),
    ]
