# Generated by Django 5.2.9 on 2026-04-29 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_projectconsolidationasset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconsolidationasset',
            name='iteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_consolidation_assets', to='management.iteration'),
        ),
        migrations.AlterField(
            model_name='projectconsolidationasset',
            name='asset_unique_identifier',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='projectconsolidationasset',
            unique_together={('iteration', 'asset_unique_identifier')},
        ),
        migrations.AddIndex(
            model_name='projectconsolidationasset',
            index=models.Index(fields=['iteration', 'asset_unique_identifier'], name='management__iterati_f8c8c1_idx'),
        ),
    ]
