# Generated by Django 5.2.9 on 2026-05-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_projectconsolidationasset_iteration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetiteration_landco',
            name='land_sales_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetiteration_landco',
            name='primary_infrastructure_module_construction_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetiteration_landco',
            name='primary_infrastructure_module_override',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assetiteration_landco',
            name='secondary_infrastructure_module_construction_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetiteration_landco',
            name='secondary_infrastructure_override',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
