# Generated by Django 5.2.9 on 2026-05-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_assetiteration_landco_land_sales_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetiteration_devco',
            name='sales_override',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assetiteration_devco',
            name='sales_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetiteration_landco',
            name='asset_operations',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assetiteration_landco',
            name='land_development',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assetiteration_landco',
            name='land_sales_override',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assetiteration_landco',
            name='vertical_development',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
