# Generated by Django 5.2.14 on 2026-05-13 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_assetiteration_devco_sales_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InflationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflation_profiles', to='management.iteration')),
            ],
            options={
                'indexes': [models.Index(fields=['iteration', 'profile_name', 'year'], name='management__iterati_0972a5_idx')],
                'unique_together': {('iteration', 'profile_name', 'year')},
            },
        ),
    ]
