# Generated by Django 5.2.14 on 2026-05-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_inflationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='unititeration_assetco',
            name='market_rent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
