# Generated by Django 5.2.14 on 2026-05-17 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_unititeration_assetco_market_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrDecomposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irr_decomposition_rows', to='management.iteration')),
            ],
            options={
                'indexes': [models.Index(fields=['iteration', 'metric_name'], name='management__iterati_366c5a_idx')],
                'unique_together': {('iteration', 'metric_name')},
            },
        ),
    ]
