# Generated by Django 5.2.14 on 2026-05-19 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_irrdecomposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitivityScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('scenario_label', models.CharField(max_length=500)),
                ('scenario_code', models.CharField(blank=True, default='', max_length=10)),
                ('param1', models.CharField(blank=True, default='', max_length=255)),
                ('param1_pct', models.CharField(blank=True, default='', max_length=20)),
                ('param2', models.CharField(blank=True, default='', max_length=255)),
                ('param2_pct', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitivity_scenarios', to='management.iteration')),
            ],
        ),
        migrations.CreateModel(
            name='SensitivityIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_devco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensitivity_rows', to='management.assetiteration_devco')),
                ('asset_landco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensitivity_rows', to='management.assetiteration_landco')),
                ('asset_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensitivity_rows', to='management.projectasset')),
                ('asset_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensitivity_rows', to='management.unititeration_assetco')),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitivity_iterations', to='management.iteration')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensitivity_iterations', to='management.dimperiod')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitivity_rows', to='management.sensitivityscenario')),
            ],
        ),
        migrations.CreateModel(
            name='GoalSeekIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('variable', models.CharField(blank=True, default='', max_length=255)),
                ('target_metric', models.CharField(blank=True, default='', max_length=255)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('base_metric_value', models.FloatField(blank=True, null=True)),
                ('pct_change_required', models.FloatField(blank=True, null=True)),
                ('achieved_metric_value', models.FloatField(blank=True, null=True)),
                ('metric_error', models.FloatField(blank=True, null=True)),
                ('model_evaluations', models.IntegerField(blank=True, null=True)),
                ('linear_pct_change', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_seek_iterations', to='management.iteration')),
            ],
            options={
                'indexes': [models.Index(fields=['iteration', 'module'], name='management__iterati_bb4f7b_idx')],
                'unique_together': {('iteration', 'module')},
            },
        ),
        migrations.AddIndex(
            model_name='sensitivityscenario',
            index=models.Index(fields=['iteration', 'module'], name='management__iterati_718b15_idx'),
        ),
        migrations.AddIndex(
            model_name='sensitivityscenario',
            index=models.Index(fields=['iteration', 'module', 'scenario_code'], name='management__iterati_01160a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sensitivityscenario',
            unique_together={('iteration', 'module', 'scenario_code')},
        ),
        migrations.AddIndex(
            model_name='sensitivityiteration',
            index=models.Index(fields=['iteration', 'module'], name='management__iterati_762ded_idx'),
        ),
        migrations.AddIndex(
            model_name='sensitivityiteration',
            index=models.Index(fields=['scenario'], name='management__scenari_c8d2e4_idx'),
        ),
        migrations.AddIndex(
            model_name='sensitivityiteration',
            index=models.Index(fields=['asset_landco'], name='management__asset_l_66e634_idx'),
        ),
        migrations.AddIndex(
            model_name='sensitivityiteration',
            index=models.Index(fields=['asset_devco'], name='management__asset_d_580d30_idx'),
        ),
        migrations.AddIndex(
            model_name='sensitivityiteration',
            index=models.Index(fields=['asset_unit'], name='management__asset_u_5fdbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='sensitivityiteration',
            index=models.Index(fields=['asset_project'], name='management__asset_p_9c3289_idx'),
        ),
    ]
